github.dismiss_out_of_range_messages

kotlin_detekt.skip_gradle_task = true
kotlin_detekt.report_file = "flowreactor/build/reports/detekt/detekt.xml"
kotlin_detekt.detekt

junit.parse "flowreactor/build/test-results/test/*.xml"
junit.report
